@extends('layouts.layout')
@section('meta-title')Guanacaste Vende | Politica de Privacidad @stop
@section('meta-description')Politica de Privacidad @stop
@section('content')
    <section class="terms">

        <h1 class="terms__title">Politica de Privacidad</h1>

        <p>Estas políticas de privacidad (las "Políticas de Privacidad") entrarán en vigor desde su aceptación para los nuevos usuarios y están vigentes desde 1º de enerol de 2015.</p>
        <p>La privacidad de la información de los usuarios es muy importante para Guanacaste Vende. Es por esa razón que se toman las precauciones y recaudos para resguardar su información, utilizando los mecanismos de seguridad informática de protección de la información más completos y eficaces.Como parte normal de nuestra actividad recogemos y, en algunos casos, revelamos información sobre nuestros usuarios y visitantes de nuestro sitio Web. Estas Políticas de Privacidad describen la información que Guanacaste Vende recoge sobre sus usuarios y visitantes y lo que puede hacerse con dicha información. Esta política es muy detallada porque es importante que todos los usuarios y visitantes de nuestro sitio Web conozcan las prácticas de Guanacaste Vende de la forma más precisa posible. Al registrarse y/o navegar el sitio Web de Guanacaste Vende, el usuario y/o el visitante presta su consentimiento para que se utilice su información personal de acuerdo a las políticas que se describen a continuación.</p>
        <p>Este documento es parte integrante de los Términos y Condiciones Generales de Guanacaste Vende. Mediante la aceptación de los Términos y Condiciones Generales en el momento de la registración el usuario acepta las políticas aquí contenidas.</p>

        <ul class="ul__numbers">
        <li>Los usuarios tienen reconocidos y podrán ejercitar los derechos de acceder, cancelar y actualizar su Información Personal, incluyendo su dirección de e-mail, así como a oponerse al tratamiento de la misma y a ser informado de las cesiones llevadas a cabo, todo ello de conformidad a lo dispuesto en la normativa aplicable. Los usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de la Información Personal facilitada, y se comprometen a mantenerla debidamente actualizada.
            Una vez registrado en Guanacaste Vende, el usuario podrá revisar y cambiar la información que nos ha enviado durante el proceso de registración incluyendo: a) el nombre de usuario-apodo y dirección de correo electrónico. Sin perjuicio de los cambios que realice, Guanacaste Vende conservará la Información Personal anterior por motivos de seguridad y control del fraude. b) la información de la registración como: compañía, domicilio, ciudad, región, código postal, número principal de teléfono, número secundario de teléfono, número de fax, correo electrónico, etc. c) la clave o password.</li>

        <li>Los usuarios deben actualizar su Información Personal periódicamente conforme vaya cambiando para que los otros usuarios puedan ubicarlos cuando realicen una operación. Para hacer cualquier modificación en la información que suministrada en el momento de la Registración, se debe ingresar en la sección Mi Perfil y hacer clic en Edita tu Perfil.</li>

        <li>Guanacaste Vende podrá modificar en cualquier momento los términos y condiciones de estas Políticas de Privacidad y confidencialidad y/o las prácticas de envío de e-mails. Si decidimos introducir algún cambio material a nuestras Políticas de Privacidad, te notificaremos publicando una versión actualizada de las Políticas en esta sección o mediante el envío de un e-mail o informándolo en la página principal u otras secciones del sitio para mantenerte actualizado de los cambios realizados. Si hacemos cambios materiales en la forma que tu Información Personal es administrada te notificaremos por e-mail para que puedas tomar una decisión informada respecto si aceptas o no que tu Información Personal sea utilizada de esa forma. Si no aceptas esos términos, en ese caso quedará disuelto el vínculo contractual y tu Información Personal no será usada de otra forma que la que fue informada al momento de recabarse.
            Para mayor información sobre la confidencialidad de tu Información Personal, contáctanos por correo electrónico a info@guanacastevende.com</li>

        <li>Lo primero que se debe hacer para disfrutar de los servicios de Guanacaste Vende es registrarse, suministrando ciertos datos personales ("Información Personal") completos y exactos. Podremos solicitar, recabar y almacenar la siguiente Información Personal: apodo o username para operar en el sitio de Guanacaste Vende, nombre, número de documento o identificación válida, información física de contacto (como número de teléfono domicilio, dirección de e-mail, etc.). Guanacaste Vende podrá confirmar los datos personales suministrados acudiendo a entidades públicas, compañías especializadas o centrales de riesgo, para lo cual nos autorizas expresamente. La información que Guancaste Vende obtenga de estas entidades será tratada en forma confidencial.</li>
        <li>El Usuario que se registre en Guanacaste Vende a través de su cuenta personal en una red social ("Cuenta Personal"), o de cualquier modo acceda a Guanacaste Vende a través de su Cuenta Personal, consiente expresamente que Guanacaste Vende:
            <ul class="ul__letters">
                <li>Tenga acceso, en cualquier momento, a la totalidad de la información contenida en su Cuenta Personal, incluyendo en particular, pero sin limitación, a su Información Personal, información sobre sus intereses, gustos, contactos y cualquier otro contenido alojado en su Cuenta Personal;</li>
                <li>incluya en dicha cuenta, mensajes, fotografías, videos y cualquier otro tipo de contenido; y</li>
                <li>envíe al correo electrónico del Usuario vinculado a la Cuenta Personal, información o mensajes con la finalidad descripta en la sección "Uso que hacemos de la Información" abajo.</li>
            </ul>
            Se acuerda expresamente que en cualquier momento el usuario registrado en Guanacaste Vende podrá solicitar la baja o cierre de su solicitud de registración, y/o el cierre de su cuenta o eliminación de su cuenta e información de la base de datos de Guanacaste Vende.
            Guanacaste Vende recoge y almacena automáticamente cierta información sobre la actividad de los usuarios y visitantes dentro de su sitio web. Tal información puede incluir la URL de la que provienen (estén o no en nuestro sitio web), a qué URL acceden seguidamente (estén o no en nuestro sitio web), qué navegador están usando, y sus direcciones IP. También las páginas visitadas, las búsquedas realizadas, las publicaciones, compras o ventas, calificaciones y réplicas ingresadas, mensajes en los foros, entre otra información podrá ser almacenada y retenida.
        Si los usuarios nos envían correspondencia sean correos electrónicos o cartas, o si otros usuarios o terceros nos envían correspondencia sobre las actividades o sobre los mensajes de otros usuarios en nuestro sitio, podemos recoger y almacenar tal Información Personal, incluyendo direcciones de e-mail.</li>
        <li>Para suministrar un excelente servicio y para que los usuarios puedan realizar operaciones en forma ágil y segura, Guanacaste Vende requiere cierta información de carácter personal, incluyendo dirección de e-mail. La recolección de información nos permite ofrecer a los usuarios servicios y funcionalidades que se adecuen mejor a sus necesidades y personalizar nuestros servicios para hacer que sus experiencias con Guanacaste Vende sean lo más cómodas posible. La Información Personal que recabamos tiene las siguientes finalidades:
            <ul class="ul__letters">
                <li> Ayudar al comprador y vendedor a entrar en contacto directo en la oportunidad que corresponda según la modalidad de la compra. En este caso, Guanacaste Vende suministrará a los interesados sus datos personales (nombre, teléfonos, localidad y correo electrónico), a través de correo electrónico o a través del sitio. La información así conocida por el comprador o el vendedor, sólo podrá ser utilizada a efectos de concluir la operación originada en Guanacaste Vende y no deberá ser empleada por ninguno de ellos con fines publicitarios o promocionales u otras actividades no relacionadas con Guanacaste Vende, salvo la expresa autorización del usuario.</li>
                <li> Desarrollar estudios internos sobre los intereses, comportamientos y demografía de los usuarios para comprender mejor sus necesidades e intereses y ofrecer mejores servicios o proveerles información relacionada.</li>
                <li> Mejorar nuestras iniciativas comerciales y promocionales y analizar las páginas visitadas las búsquedas realizadas por los usuarios, para mejorar nuestra oferta de contenidos y artículos, personalizar dichos contenidos, su presentación y servicios.</li>
                <li> Enviar información o mensajes por e-mail sobre nuevos servicios, mostrar publicidad o promociones, banners, de interés para nuestros usuarios, noticias sobre Guanacaste Vende, además de la información expresamente autorizada en la sección de preferencias. Si el usuario lo prefiere, puede solicitar que lo excluyan de las listas para el envío de información promocional o publicitaria.</li>
                <li> Los ganadores de las Promociones y/o concursos realizados por Guanacaste Vende autorizan expresamente a difundir sus nombres, datos personales e imágenes y los de sus familias, por los medios y en las formas que consideren convenientes, con fines publicitarios y/o promocionales, sin derecho a compensación alguna.</li>
                <li> Compartir la información Personal (incluyendo dirección de e-mail) con los proveedores de servicios o las empresas de "outsourcing" que contribuyan a mejorar o facilitar las operaciones a través de Guanacaste Vende, como (sin limitarse a) servicios de transporte, medios de pago, seguros o intermediarios en la gestión de pagos, call centers o programas de fidelidad, entre otros. Guanacaste Vende velará porque se cumplan ciertos estándares, mediante la firma de acuerdos o convenios cuyo objeto sea la privacidad de los datos personales de nuestros usuarios. No obstante, Guanacaste Vende no se hace responsable por el uso indebido de la Información Personal del usuario que hagan estas compañías o sitios de Internet. En algunos casos, estos proveedores de servicios serán quienes recojan información directamente del usuario (por ejemplo si les solicitamos que realicen encuestas o estudios). En tales casos, podrá recibir una notificación acerca de la participación de un proveedor de servicios en tales actividades, y quedará a discreción del usuario toda la información que quiera brindarle y los usos adicionales que los proveedores decidan hacer. En caso de que facilites, por propia iniciativa información adicional a dichos prestadores de servicios directamente, tales Prestadores usarán esta información conforme a sus propias políticas de privacidad. Si decidimos revelar o compartir Información Persona con terceros que no son proveedores de servicios o empresas afiliadas o relacionadas con Guanacaste Vende, requeriremos tu consentimiento.</li>
                <li> Suministrar la información personal de los usuarios a las entidades que intervengan en la resolución de disputas entre los mismos, tales como: Compañías de Seguros, Amigables Componedores o Tribunales de Arbitraje o tribunales competentes para solucionar tales disputas.</li>
            </ul>
        </li>


        <li>Una vez registrado en su sitio Web, Guanacaste Vende no venderá, alquilará o compartirá la Información Personal excepto en las formas establecidas en estas políticas. Sin perjuicio de ello, el usuario consiente en forma expresa que Guanacaste Vende  transfiera total o parcialmente la Información Personal a cualquiera de las sociedades controladas, controlantes y/o vinculadas con Guanacaste Vende , a cualquier título y en el momento, forma y condiciones que estime pertinentes. Haremos todo lo que esté a nuestro alcance para proteger la privacidad de la información. Puede suceder que en virtud de órdenes judiciales, o de regulaciones legales, nos veamos compelidos a revelar información a las autoridades o terceras partes bajo ciertas circunstancias, o bien en casos que terceras partes puedan interceptar o acceder a cierta información o transmisiones de datos en cuyo caso Guanacaste Vende no responderá por la información que sea revelada.

        <li>Para acceder a los servicios reservados únicamente para los usuarios debidamente registrados los usuarios dispondrán de una clave personal. Con ella podrán comprar, vender, ofertar, calificar, entre otras actividades. Esta clave deben mantenerla bajo absoluta confidencialidad y, en ningún caso, deberán revelarla o compartirla con otras personas. El usuario será responsable de todos los actos que tengan lugar mediante el uso de su Apodo-username y Clave, lo que incluye hacerse cargo del pago de las tarifas que eventualmente se devenguen o por los perjuicios que puedan sufrir otros usuarios por tal motivo. Si por cualquier razón un usuario creyera que alguien puede conocer su clave, deberá modificarla ingresando desde el menú de navegación en Perfil y una vez allí hacer clic en Edita tu Perfil.
        <li>Nuestros servicios sólo están disponibles para aquellas personas que tengan capacidad legal para contratar. Por lo tanto, aquellos que no cumplan con esta condición deberán abstenerse de suministrar información personal para ser incluida en nuestras bases de datos. Sin embargo, pueden hacerlo a través de los padres o tutores.
        <li>Para facilitar la interacción entre todos los miembros de la comunidad de Guanacaste Vende, nuestro servicio permite un acceso limitado a ciertos datos de contacto del resto de usuarios, tales como Nombre de usuario, Teléfonos, Ciudad y dirección de correo electrónico. Los usuarios sólo podrán utilizar la Información Personal de otros usuarios obtenida en el sitio para: (a) comunicaciones relacionadas con Guanacaste Vende que no constituyan comunicaciones comerciales no solicitadas, (b) consultar sobre: depósito, seguros, envío o transporte y reclamaciones sobre fraude, y (c) cualquier otra finalidad a la que el usuario correspondiente consienta expresamente una vez le hayan sido comunicadas previamente la información legalmente requerida. Bajo ninguna circunstancia, se debe comunicar Información Personal o dirección de correo electrónico de otro usuario a ningún tercero sin nuestro consentimiento y el del usuario afectado. No se debe agregar a la agenda de direcciones de correo electrónico (física o electrónica) los datos de ningún usuario de Guanacaste Vende, ni siquiera los datos de quienes hayan adquirido algún artículo ofrecido en Guanacaste Vende, sin que medie el consentimiento expreso de tal usuario.</li>
        <li>El usuario y el visitante del sitio Web de Guanacaste Vende conoce y acepta que Guanacaste Vende podrá utilizar un sistema de seguimiento mediante la utilización de cookies (las "Cookies"). Las Cookies son pequeños archivos que se instalan en el disco rígido, con una duración limitada en el tiempo que ayudan a personalizar los servicios. También ofrecemos ciertas funcionalidades que sólo están disponibles mediante el empleo de Cookies. Las Cookies se utilizan con el fin de conocer los intereses, el comportamiento y la demografía de quienes visitan o son usuarios de nuestro Sitio Web y de esa forma, comprender mejor sus necesidades e intereses y darles un mejor servicio o proveerle información relacionada. También usaremos la información obtenida por intermedio de las Cookies para analizar las páginas navegadas por el visitante o usuario, las búsquedas realizadas, mejorar nuestras iniciativas comerciales y promocionales, mostrar publicidad o promociones, banners de interés, noticias sobre Guanacaste Vende, perfeccionar nuestra oferta de contenidos y artículos, personalizar dichos contenidos, presentación y servicios; también podremos utilizar Cookies para promover y hacer cumplir las reglas y seguridad del sitio. 12-Guanacaste Vende podrá agregar Cookies en los e-mails que envíe para medir la efectividad de las promociones. Utilizamos adicionalmente las Cookies para que el usuario no tenga que introducir su clave tan frecuentemente durante una sesión de navegación, también para contabilizar y corroborar las registraciones, la actividad del usuario y otros conceptos  y acuerdos comerciales, siempre teniendo como objetivo de la instalación de las Cookies, el beneficio del usuario que la recibe, y no será usado con otros fines ajenos a Guanacaste Vende. Se establece que la instalación, permanencia y existencia de las Cookies en el computador del usuario depende de su exclusiva voluntad y puede ser eliminada de su computador cuando el usuario así lo desee. Adicionalmente, se pueden encontrar Cookies u otros sistemas similares instalados por terceros en ciertas páginas de nuestro sitio Web. Por ejemplo, al navegar por una página creada por un usuario, puede que exista una Cookie emplazada en tal página. Se aclara expresamente que estas políticas cubre la utilización de Cookies por este sitio y no la utilización de Cookies por parte de anunciantes. Nosotros no controlamos el uso de Cookies por terceros.</li>
        <li>Un Web beacon es una imagen electrónica, también llamada single-pixel (1 x 1) o pixel transparente, que es colocada en código de una página Web. Un Web beacon tiene finalidades similares a las Cookies. Adicionalmente un Web beacon es utilizado para medir patrones de tráfico de los usuarios de una página a otra con el objeto de maximizar como fluye el tráfico a través de la Web. El usuario y el visitante del sitio Web de Guanacaste Vende conoce y acepta que Guanacaste Vende podrá utilizar un sistema de seguimiento mediante la utilización de Web beacons.</li>
        <li>Si escoges enviarle un producto a un amigo, mediante nuestra plataforma, Guanacaste Vende podrá requerir el nombre y correo electrónico de la persona a quien se le remita. A través de esta funcionalidad, Guanacaste Vende enviará un e-mail automático invitándolo a visitar cierto producto en el sitio Web. Guanacaste Vende utilizará el correo electrónico de la persona a quien se le remita sólo para enviarle esta comunicación y posterior seguimiento, sin embargo dicha información no será almacenada. De acuerdo a su Política de Privacidad, Guanacaste Vende toma los recaudos necesarios para evitar el envío no solicitado de e-mails. Además Guanacaste Vende y sus usuarios no aceptan el "spamming" o envío no solicitado de correos electrónicos. Por ello se establece que está absolutamente prohibida la utilización del servicio Envíale este artículo a un amigo con fines de spam, o envío indiscriminado de mensajes de cualquier naturaleza por correo electrónico, con cualquier finalidad que esto se realice. Por favor, no les envíes este tipo de mensajes a quienes así te lo soliciten. Guanacaste Vende podrá suspender o inhabilitar definitivamente a aquellos usuarios que utilicen este servicio con los fines de promocionar sus artículos a la venta o cualquier otro fin distinto al previsto por este servicio y que sean denunciados por aquellas personas que reciben tales mensajes.</li>
        <li>Guanacaste Vende coopera con las autoridades competentes y con otros terceros para garantizar el cumplimiento de las leyes, por ejemplo en materia de protección de derechos de propiedad industrial e intelectual, prevención del fraude y otras materias. Guanacaste Vende podrá revelar la Información Personal de sus usuarios bajo requerimiento de la autoridades judiciales o gubernamentales competentes para efectos de investigaciones conducidas por ellas, aunque no exista una orden ni una citación ejecutiva o judicial, o por ejemplo (y sin limitación a este supuesto) cuando se trate de investigaciones de carácter penal o de fraude o las relacionadas con piratería informática o la violación de derechos de autor. En tales situaciones, Guanacaste Vende colaborará con las autoridades competentes con el fin de salvaguardar la integridad y la seguridad de la Comunidad y la de sus usuarios. Guanacaste Vende puede (y los usuarios lo autorizan expresamente) comunicar cualquier Información Personal sobre sus usuarios con la finalidad de cumplir la normativa aplicable y cooperar con las autoridades competentes en la medida en que discrecionalmente lo entendamos necesario y adecuado en relación con cualquier investigación de un ilícito o un fraude, infracción de derechos de propiedad industrial o intelectual, u otra actividad que sea ilegal o que pueda exponer a Guanacaste Vende o a sus usuarios a cualquier responsabilidad legal. Además, podemos (y los usuarios lo autorizan expresamente) comunicar su nombre completo, apodo, domicilio, ciudad, región, código postal, país, número de teléfono, dirección de correo electrónico, etc.en la forma que, a nuestra discreción, entendamos necesaria o adecuada en relación con la investigación del fraude, infracción de derechos de propiedad industrial o intelectual, piratería, o cualquier otra actividad ilegal. Este derecho será ejercido por Guanacaste Vende a efectos de cooperar con el cumplimiento y ejecución de la ley, independientemente que no exista una orden judicial o administrativa al efecto. Además, Guanacaste Vendese reserva el derecho (y nos autorizas expresamente a ello) de comunicar información sobre sus usuarios a otros usuarios, entidades o terceros cuando haya motivos suficientes para considerar que la actividad de un usuario sea sospechosa de intentar o cometer un delito o intentar perjudicar a otras personas. Este derecho será utilizado por Guanacaste Vende a su entera discreción cuando lo considere apropiado o necesario para mantener la integridad y la seguridad de la Comunidad y la de sus usuarios, para hacer cumplir los Términos y Condiciones Generales y demás Políticas del sitio y a efectos de cooperar con la ejecución y cumplimiento de la ley. Este derecho será ejercido por Guanacaste Vende independientemente que no exista una orden judicial o administrativa al efecto.</li>
        <li>Guanacaste Vende está obligado a cumplir con toda la normativa aplicable en materia de medidas de seguridad aplicables a la Información Personal. Adicionalmente, Guanacaste Vende usa los estándares de la industria entre materia de protección de la confidencialidad de su Información Personal, incluyendo, en otras medidas, cortafuegos ("firewalls") y Secure Socket Layers ("SSL"). Guanacaste Vende considera a los datos de sus usuarios como un activo que debe ser protegido de cualquier pérdida o acceso no autorizado. Empleamos diversas técnicas de seguridad para proteger tales datos de accesos no autorizados por usuarios de dentro o fuera de nuestra compañía. Sin embargo, es necesario tener muy en cuenta que la seguridad perfecta no existe en Internet.Por ello, Guanacaste Vende no se hace responsable por interceptaciones ilegales o violación de sus sistemas o bases de datos por parte de personas no autorizadas. Guanacaste Vende, tampoco se hace responsable por la indebida utilización de la información obtenida por esos medios. Todos los datos personales de los usuarios serán almacenados en un fichero automatizado de datos personales. El fichero de Datos Personales de los usuarios de Guanacaste Vende reside en EE.UU. El usuario al registrarse en Guanacaste Vende confirma que está informado de la residencia de este fichero y autoriza esta transferencia internacional de sus datos.</li>
        <li>Sin perjuicio que Guanacaste Vende quiere mantener a sus usuarios actualizados en todo momento sobre promociones, novedades, cambios, etc. los usuarios pueden seleccionar los e-mails e información promocional que gustarían recibir de Guanacaste Vende.</li>
        </ul>
    </section>

@stop
